Converting Types from js to ts
projecttacoma/cql-module-generator pull request #5
Opened 2021-08-11 15:06 UTC by MegRiley

# Summary
This PR uses existing types from [the original module builder](https://github.com/synthetichealth/module-builder/tree/master/src/types) and converted them to typescript. 
## New behavior
When running the CLI, there is no new behavior (there is no output). 
## Code changes
The following files were created: 

- attributes.ts - this file contains
- code.ts - this file defines the type for the code object that is used throughout states.ts (and with the addition of this file I updated states.ts to use this new type)
- conditional.ts- This file defines various types  such as SocioeconomicStatusConditional and more basic ones like AndConditional
- Module.ts- This file just defines the type module making use of BaseState 
- Transition.ts - This file defines the different types of transition 
- Unit.ts - this file contains the definitions for UnitOfTime and UnitOfAge types

# Testing guidance
There is no specific testing guidance for this change, however any tests that had passed previously against states.ts should still be passing

2021-08-12 18:07 UTC, mgramigna requested changes
small comments

2021-08-12 18:07 UTC, mgramigna commented on src/states/factory.ts
> +import { code } from '../types/code';
Lint is saying this import is never used

2021-08-12 18:07 UTC, mgramigna commented on src/types/code.ts
> +import { type } from 'os';
I think this import was added by mistake

2021-08-12 18:07 UTC, mgramigna commented on src/types/conditional.ts
> +// @flow
the `@flow` stuff was used for synthea-specific reasons. We don't need it 
```suggestion
```

2021-08-12 18:07 UTC, mgramigna commented on src/types/code.ts
> +export type code = {
```suggestion
export type Code = {
```

can we capitalize this type?

2021-08-12 18:07 UTC, mgramigna commented on src/types/code.ts
> +  value_set: string;
```suggestion
  value_set?: string;
```

I think value_set should be optional

2021-08-16 21:24 UTC, hossenlopp approved these changes

2021-08-16 21:25 UTC, merged